apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    department: engineering
    app: nginx
spec:
  containers:
  - name: nginx
    image: europe-west2-docker.pkg.dev/argolis-test-1/source-to-prod-demo/nginx:123
    imagePullPolicy: Always
    ports:
    - containerPort: 80
